spring:
  profiles:
    active: query

  application:
    name: demo

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: llama3.1
          temperature: 0

      embedding:
        options:
          model: nomic-embed-text

    model:
      embedding: ollama

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000

        collection-name: hs-codes
        initialize-schema: true