spring:
  application:
    name: demo
  profiles:
    active: default

  ai:
    vertex:
      ai:
        gemini:
          project-id: proyectofinalmaestria-493719
          location: us-central1
          chat.options.model: gemini-2.5-flash
        embedding:
          project-id: proyectofinalmaestria-493719
          location: us-central1
    vectorstore:
      mongodb:
        initialize-schema: true
        collection-name: hscodes

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: proyectomaestria